### ISSUE TITLE
[feature] See exact position

### ISSUE THREAD

**Issue by Bruno-mp4** [JumpKingPlus/JumpKingPlus#33]
yo popo,

uhhhh can you add a toggleable feature (like the progression %) that instead shows the exact x and y position on the king on the map.
a similar feature is available in jumpkingmanager. If you click "save position" it shows exact x and y.

tyty, dabrunL

**Comment by Phoenixx19** [comment]
Done in https://github.com/JumpKingPlus/JumpKing/commit/45cbdc2023c221387ec7cc75bd66ea824f41e0e7.
