### ISSUE TITLE
[feature] Show exact frames of a jump instead of %

### ISSUE THREAD

**Issue by Bruno-mp4** [JumpKingPlus/JumpKingPlus#34]
yo popo,
make it toggalable, ty

**Comment by Phoenixx19** [comment]
Added base data for both code (https://github.com/JumpKingPlus/JumpKing/commit/c28774a806f1123787c89147e482c32eb8b7fb09) and library (https://github.com/JumpKingPlus/JumpKingPlus/commit/9b7023229840010c3d740cfb9abcb58e5b86c955).

![unknown](https://user-images.githubusercontent.com/41084138/181994919-d0c5de5d-7b77-4c22-bdbe-437aedacd7fb.png)

### To do
- [ ] Add option to save choice on `.config` file.

**Comment by Phoenixx19** [comment]
Completed in https://github.com/JumpKingPlus/JumpKing/commit/d5fcf2d1b316a16278370e5949ea2c284b04244f.
