### ISSUE TITLE
it says its downloaded and on my jump king file but nothing has changed

### ISSUE THREAD

**Issue by jacobiemcnoglie** [JumpKingPlus/JumpKingPlus#35]
its just regular jump king and it says i have jk plus downloaded and on the file idk if this is something with the mod or maybe i messed it up i was wondering if someone would be able to help me?

**Comment by Phoenixx19** [comment]
If you don't see a text on the main menu saying "Using JumpKing v`x.x.x`" then it probably didn't succeed in installing.
Try uninstalling and reinstalling JumpKingPlus again through Control Panel or Settings.
If you still have issues, I recommend joining the **[Discord server](https://discord.gg/dUk9FPDNVq)** but you can also use this issue you've opened.

**Comment by Phoenixx19** [comment]
Closed for inactivity.
