### ISSUE TITLE
No restart button in pause menu

### ISSUE THREAD

**Issue by lemon1018007101** [JumpKingPlus/JumpKingPlus#36]
I've just installed the latest version of jump king plus(v1.8.1b), but I can't find the restart button in pause menu, neither can I quick restart by pressing Q. Other functions just work normally, I've also uninstalled and installed it again for several times but in vain, what can I do? 
![螢幕擷取畫面 (53)](https://user-images.githubusercontent.com/116615830/197675368-b885e1c7-7d06-4eb2-bf33-2734bdb065a9.png)
![螢幕擷取畫面 (55)](https://user-images.githubusercontent.com/116615830/197675426-66147a24-a22f-410e-994f-fcaf957754e9.png)
![螢幕擷取畫面 2022-10-25 112538](https://user-images.githubusercontent.com/116615830/197675500-e64691b5-8802-401d-8209-e2f34ee1b0ce.jpg)
![螢幕擷取畫面 (58)](https://user-images.githubusercontent.com/116615830/197675782-6f3125e8-2731-40e4-b6df-f6404e36f808.png)

**Comment by Phoenixx19** [comment]
Set boomerProofRestart to false.

**Comment by lemon1018007101** [comment]
Oh it works! Thank you so much!
