### ISSUE TITLE
Crash at launching the game

### ISSUE THREAD

**Issue by KanzakiShiMae** [JumpKingPlus/JumpKingPlus#37]
I've been installing jump king in steam and it keeps crashing when i launch it. I tried to change the language of the game to English but it keeps happening, and only when i install this mod. 
![image](https://user-images.githubusercontent.com/122336129/211460522-ae96147a-4fcd-4247-bd36-619b9535102f.png)

**Comment by Phoenixx19** [comment]
Make a folder called `wardrobe` in `Jump King/Content`. Thanks for the feedback, I'll fix the installer later.
