### ISSUE TITLE
trojan found when installing the new update.

### ISSUE THREAD

**Issue by Flaming59** [JumpKingPlus/JumpKingPlus#39]
so me and my friend downloaded the mod last year. it was so fun and we wanted to play it again and we noticed a new update. but when my friend was downloading the new update the antivirus he has spotted a trojan. so obvi he didn't install the new update and i ain't gonna like. install it cuz of that.

**Comment by Phoenixx19** [comment]
It's a false positive, Microsoft (and so Windows) doesn't like the installer much, that's why I've sourced all the complaints in the [Transparency page](https://jumpkingplus.github.io/transparency/). Sorry about that.. 😥

**Comment by PhantomBadger** [comment]
I can back this up - had the same occur on my end but multiple virus scans with different software produced no actual cause for concern. Likely a red herring :)

**Comment by Flaming59** [comment]
ooh okay i see. i'm just glad it isn't anything bad... we were scared when it popped up haha! but thank u for responding tho and clearing it up!

**Comment by Phoenixx19** [comment]
Closing the issue if the issue has been resolved.
